version: 2.1

orbs:
  # This uses the Orbs located at https://github.com/wordpress-mobile/circleci-orbs
  ios: wordpress-mobile/ios@1.0
  git: wordpress-mobile/git@1.0
  slack: circleci/slack@3.4.2

jobs:
  Test:
    executor:
      name: ios/default
      xcode-version: "11.6.0"
    steps:
      - git/shallow-checkout
      - ios/test:
          xcode-version: "11.6.0"
          scheme: SimplenoteFoundation
          device: iPhone 11

workflows:
  simplenote_foundation:
    jobs:
      - Test
